services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NFTMAREKTPLACE_DB_DATABASE}
      POSTGRES_USER: ${NFTMAREKTPLACE_DB_USERNAME}
      POSTGRES_PASSWORD: ${NFTMAREKTPLACE_DB_PASSWORD}
    ports:
      - "${NFTMAREKTPLACE_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql

volumes:
  psql_volume_bp:
